namespace Nikkiward.Models;

/// <summary>
/// The three independent identity axes used by a launch profile.
/// A profile selection never changes any of these values at runtime.
/// </summary>
public enum RegionFamily
{
    Unknown,
    MainlandChina,
    Overseas,
}

public enum DistributionChannel
{
    Unknown,
    Official,
    Steam,
    Epic,
    Bilibili,
}

public enum AccountAuthority
{
    Unknown,
    Papergames,
    Infold,
    Steam,
    Bilibili,
}

public enum ProfileDiscoverySource
{
    Unknown,
    ManualSelection,
    LauncherRegistry,
    LauncherConfig,
    SteamRegistry,
    SteamLibraryManifest,
    ChannelStoreReceipt,
}

public enum InstallationCandidateState
{
    NotFound,
    Downloading,
    Incomplete,
    Candidate,
    ReadyForStaticVerification,
    Unsupported,
}

public enum ProfileBuildFailureCode
{
    None,
    InvalidRequest,
    LauncherRootNotFound,
    BackendRootNotFound,
    GameRootNotFound,
    AmbiguousLauncherRoot,
    AmbiguousGameRoot,
    LayoutMismatch,
    UnsupportedVersion,
    SteamManifestMissing,
    SteamNotReady,
    ProviderContractUnavailable,
    ChannelMismatch,
    ChannelMarkerMissing,
    ChannelMarkerMismatch,
    ConflictingInstallation,
    MetadataReadFailed,
}

public sealed record ProfileBuildRequest
{
    public DistributionChannel Channel { get; init; } = DistributionChannel.Unknown;

    public string? ProfileId { get; init; }

    public string? DisplayName { get; init; }

    /// <summary>
    /// Optional user-selected game directory. It is a hint only; the builder
    /// still verifies the complete expected layout before returning a binding.
    /// </summary>
    public string? ManualGameRootPath { get; init; }

    /// <summary>
    /// Optional user-selected launcher root. It is kept separate from the
    /// xstarter version directory because the official backend's working
    /// directory is the launcher root.
    /// </summary>
    public string? ManualLauncherRootPath { get; init; }

    public bool AllowAutomaticDiscovery { get; init; } = true;
}

public sealed record ProfileIdentity
{
    public RegionFamily RegionFamily { get; init; } = RegionFamily.Unknown;

    public DistributionChannel DistributionChannel { get; init; } = DistributionChannel.Unknown;

    public AccountAuthority AccountAuthority { get; init; } = AccountAuthority.Unknown;

    public string? SteamAppId { get; init; }

    public string? SteamSubId { get; init; }

    public string? SteamDepotId { get; init; }

    public string? SteamBuildId { get; init; }

    public string? SteamManifestId { get; init; }
}

public sealed record SteamManifestEvidence
{
    public string ManifestPath { get; init; } = string.Empty;

    public string? AppId { get; init; }

    public string? InstallDirectoryName { get; init; }

    public string? StateFlags { get; init; }

    public long? SizeOnDisk { get; init; }

    public string? BuildId { get; init; }

    public IReadOnlyList<string> InstalledDepotIds { get; init; } = Array.Empty<string>();

    public string? SubId { get; init; }

    public string? DepotId { get; init; }

    public string? ManifestId { get; init; }

    public string? CommonInstallPath { get; init; }

    public string? StagingPath { get; init; }

    public bool IsCompleteInstall { get; init; }
}

/// <summary>
/// A provider binding is generated by code, not accepted from UserSettings.
/// ArgumentList contains only Nikkiward's own fixed preset and never contains
/// downstream authentication data.
/// </summary>
public sealed record LaunchProviderBinding
{
    public string ProviderId { get; init; } = string.Empty;

    public int ContractVersion { get; init; }

    public string BackendExecutablePath { get; init; } = string.Empty;

    public string WorkingDirectory { get; init; } = string.Empty;

    public string ArgumentPresetId { get; init; } = string.Empty;

    public IReadOnlyList<string> ArgumentList { get; init; } = Array.Empty<string>();

    public LaunchCapability MaximumCapability { get; init; } = LaunchCapability.OfficialAssisted;

    /// <summary>
    /// Kept false until the separate runtime verifier has produced a valid
    /// receipt. A discovered profile is never executable merely because it was
    /// serialized in settings.
    /// </summary>
    public bool ExecutionEnabled { get; init; }
}

public sealed record InstallationProfileCandidate
{
    public string ProfileId { get; init; } = string.Empty;

    public string DisplayName { get; init; } = string.Empty;

    public ProfileIdentity Identity { get; init; } = new();

    public InstallationCandidateState State { get; init; } = InstallationCandidateState.NotFound;

    public ProfileDiscoverySource DiscoverySource { get; init; } = ProfileDiscoverySource.Unknown;

    public string? LauncherRootPath { get; init; }

    public string? GameRootPath { get; init; }

    public LaunchProfile? Profile { get; init; }

    public LaunchProviderBinding? Provider { get; init; }

    public SteamManifestEvidence? SteamManifest { get; init; }

    public IReadOnlyList<string> MissingComponents { get; init; } = Array.Empty<string>();

    public ProfileBuildFailureCode FailureCode { get; init; } = ProfileBuildFailureCode.None;

    public string? Detail { get; init; }

    public DateTimeOffset ObservedAtUtc { get; init; } = DateTimeOffset.UtcNow;
}

public sealed record ProfileBuildResult
{
    public IReadOnlyList<InstallationProfileCandidate> Candidates { get; init; } = Array.Empty<InstallationProfileCandidate>();

    public bool HasCandidate => Candidates.Any(candidate =>
        candidate.State is InstallationCandidateState.Candidate or InstallationCandidateState.ReadyForStaticVerification);

    public InstallationProfileCandidate? SelectableCandidate => Candidates.FirstOrDefault(candidate =>
        candidate.State is InstallationCandidateState.Candidate or InstallationCandidateState.ReadyForStaticVerification);
}
